language: python

python:
  - "3.9"

# command to install dependencies
before_install:
  - mkdir logs
  - pip install -U pip
  - python setup.py install

install:
  - pip install -r requirements.txt
  - pip install .

# command to run tests
script: py.test
